### ISSUE TITLE
__init__() takes 3 positional arguments but 6 were given

### ISSUE THREAD

**Issue by Lance621** [0xHJK/dumpall#16]
Module: dumpall.addons.dsdumper

('__init__() takes 3 positional arguments but 6 were given',)
Traceback (most recent call last):
  File "/Users/**/dumpall/dumpall/__init__.py", line 41, in start
    dumper = addon.Dumper(url, outdir, proxy=proxy, force=force, debug=debug)
  File "/Users/**/dumpall/dumpall/addons/dsdumper.py", line 26, in __init__
    super(Dumper, self).__init__(url, outdir, *kwargs)
TypeError: __init__() takes 3 positional arguments but 6 were given

系统：10.15.7
环境：Python 3.9.12

**Comment by drrible** [comment]
@HeyManMan 
 next logic

**Comment by cr1bug** [comment]
Me too
win10 
python 3.8.10
![image](https://user-images.githubusercontent.com/54324046/201505859-59ea0601-f804-4230-81a4-811695695332.png)
