### ISSUE TITLE
运行报错，无法得到结果

### ISSUE THREAD

**Issue by wuxin-com** [0xHJK/dumpall#27]
运行完毕显示
“'ulimit' 不是内部或外部命令，也不是可运行的程序
或批处理文件。Module: dumpall.addons.dsdumper”
然后结果是报404的，upload/file upload/file里面什么也没有

**Comment by cornradio** [comment]
(13, 'Permission denied')
Traceback (most recent call last):
  File "C:\Users\jzyan\AppData\Local\Programs\Python\Python311\Lib\site-packages\dumpall\__init__.py", line 43, in start
    asyncio.run(dumper.start())
  File "C:\Users\jzyan\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\jzyan\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jzyan\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jzyan\AppData\Local\Programs\Python\Python311\Lib\site-packages\dumpall\addons\gitdumper.py", line 20, in start
    await self.dump()
  File "C:\Users\jzyan\AppData\Local\Programs\Python\Python311\Lib\site-packages\dumpall\addons\gitdumper.py", line 25, in dump
    idxfile = await self.indexfile(self.base_url + "/index")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jzyan\AppData\Local\Programs\Python\Python311\Lib\site-packages\dumpall\dumper.py", line 109, in indexfile
    with open(idxfile.name, "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\jzyan\\AppData\\Local\\Temp\\tmpq9se2ttr'
